services:
  db:
    image: postgres:16
    container_name: expense-tracker-postgres
    restart: always
    environment:
      POSTGRES_USER: expense_user
      POSTGRES_PASSWORD: expense_pass
      POSTGRES_DB: expense_tracker
      # Fixes the timezone issue inside the container
      TZ: Asia/Kolkata
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: