spring:
  application:
    name: expense-tracker

  datasource:
    url: jdbc:postgresql://localhost:5433/expense_tracker
    username: expense_user
    password: expense_pass
    driver-class-name: org.postgresql.Driver

# if unknown fields are sent in the payload.
  jackson:
    deserialization:
      fail-on-unknown-properties: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
# TO-DO: timezone issue: JDBC needs Asia/Calcutta, Postgres needs Asia/Kolkata
# current fix: intelliJ config changed

  flyway:
    enabled: true

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 86400000